---
- name: Show sha
  debug:
    msg: "{{ hostvars['master']['kubeadm_join'][0] }}"
- name: Join Kubernetes Cluster
  become: yes
  shell: "{{ hostvars['master']['kubeadm_join'][0] }} --ignore-preflight-errors=Swap"
  