---
- name:    Initialise Kubernetes Cluster
  become:  yes
  shell:   kubeadm init --apiserver-advertise-address={{ kubernetes_master_ip }} --pod-network-cidr=10.244.0.0/16 --kubernetes-version=v1.9.1 --ignore-preflight-errors=Swap
  register: results

- debug:
    msg: "result = {{ results.stdout }}"

- local_action: copy content="{{ results.stdout }}" dest="./kubeadm_auth.txt"

- set_fact:
    kubeadm_join: "{{ results.stdout | regex_search(regexp,'\\1') }}"
  vars:
    regexp: "(kubeadm join.*)"

- debug:
    var: kubeadm_join

- name: Copy kubernetes admin cfg
  command: cp /etc/kubernetes/admin.conf {{ ansible_env.HOME}}/
  become: yes

- name: Change admin cfg owner
  file:
    path: "{{ ansible_env.HOME}}/admin.conf"
    owner: "{{ansible_user_uid}}"
    group: "{{ansible_user_gid}}"
  become: yes

- name: Add env to bashrc
  lineinfile:
    dest: '{{ansible_env.HOME}}/.bashrc'
    insertbefore: 'EOF'
    line: 'export KUBECONFIG={{ansible_env.HOME}}/admin.conf'

- name: Export env
  shell: "export KUBECONFIG={{ansible_env.HOME}}/admin.conf"

- name: Get Flannel
  get_url: 
    url: https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml?raw=true
    dest: "{{ansible_env.HOME}}/kube-flannel.yml"
    mode: 0777

- name:    Apply Flannel
  environment:
    KUBECONFIG: "{{ansible_env.HOME}}/admin.conf"
  shell:   "kubectl create -f {{ansible_env.HOME}}/kube-flannel.yml"